name: CD - Push Docker Image to GHCR

on:
  push:
    tags:
      - "v*"

env:
  GHCR_IMAGE: ghcr.io/kharon-labs/kharon-user-management:${{ github.ref_name }}

jobs:
  build-and-push:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t $GHCR_IMAGE \
            -t local-test-image \
            .

      - name: Run smoke test before push
        run: |
          echo "🔍 Running config sanity check..."
          docker run --rm \
            -e PORT=8001 \
            -e DATABASE_URL=dummy \
            -e JWT_SECRET=dummy \
            -e IP_INFO_TOKEN=dummy \
            -e FLUTTERWAVE_SECRET_KEY=dummy \
            -e FLUTTERWAVE_PAYMENT_URL=https://dummy \
            -e FLUTTERWAVE_CALLBACK_URL=https://dummy \
            -e FLUTTERWAVE_SECRET_HASH=dummy \
            local-test-image || (echo "❌ Image did not run successfully!" && exit 1)

      - name: Push Docker image to GHCR
        run: |
          docker push $GHCR_IMAGE

      - name: Output success
        run: echo "✅ Image pushed to GHCR as $GHCR_IMAGE"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
